#!/bin/bash
  
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=80GB
#SBATCH --time=2:00:00
#SBATCH --account=yzhao010_1531

module purge
module load gcc/11.3
module load openblas/0.3.28
module load python

source /scratch1/akarande/music2latent-encoder-training/env/bin/activate
cd /scratch1/akarande/music2latent-encoder-training/music2latent
python3 train_m2l_encoder.py